"""add study session length

Revision ID: 072e0ff64666
Revises: 8c9140ae4ecc
Create Date: 2026-09-25 00:09:45.247930

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "072e0ff64666"
down_revision: str | Sequence[str] | None = "8c9140ae4ecc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans",
        sa.Column("session_minutes", sa.Integer(), server_default="60", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "session_minutes")
    # ### end Alembic commands ###
