"""add source documents

Revision ID: 234d61e05527
Revises: 50af5e5953c1
Create Date: 2026-09-23 19:12:51.191912

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "234d61e05527"
down_revision: str | Sequence[str] | None = "50af5e5953c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["topic_nodes.id"],
            name=op.f("fk_source_documents_node_id_topic_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "node_id", "url", name=op.f("uq_source_documents_node_id_url")
        ),
    )
    op.create_index(
        op.f("ix_source_documents_node_id"),
        "source_documents",
        ["node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_documents_node_id"), table_name="source_documents")
    op.drop_table("source_documents")
    # ### end Alembic commands ###
