"""add relationship memory

Revision ID: 2d886ad8383e
Revises: d9e6405561af
Create Date: 2026-09-23 19:50:37.511614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d886ad8383e"
down_revision: str | Sequence[str] | None = "d9e6405561af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relationship_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_relationship_memory_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_memory")),
        sa.UniqueConstraint(
            "user_id", "for_date", name=op.f("uq_relationship_memory_user_id_for_date")
        ),
    )
    op.create_index(
        op.f("ix_relationship_memory_user_id"),
        "relationship_memory",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_relationship_memory_user_id"), table_name="relationship_memory"
    )
    op.drop_table("relationship_memory")
    # ### end Alembic commands ###
