"""add check-in reflections

Revision ID: 3e0af845151c
Revises: 40f33ae602e0
Create Date: 2026-09-25 00:26:29.768730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e0af845151c"
down_revision: str | Sequence[str] | None = "40f33ae602e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("study_checkins", sa.Column("feeling", sa.Text(), nullable=True))
    op.add_column("study_checkins", sa.Column("fuzzy", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study_checkins", "fuzzy")
    op.drop_column("study_checkins", "feeling")
    # ### end Alembic commands ###
