"""allow a study retry

Revision ID: 40f33ae602e0
Revises: 072e0ff64666
Create Date: 2026-09-25 00:15:20.435352

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40f33ae602e0"
down_revision: str | Sequence[str] | None = "072e0ff64666"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_study_sessions_node_id"), "study_sessions", type_="unique"
    )
    op.create_index(
        op.f("ix_study_sessions_node_id"), "study_sessions", ["node_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_study_sessions_node_id"), table_name="study_sessions")
    op.create_unique_constraint(
        op.f("uq_study_sessions_node_id"),
        "study_sessions",
        ["node_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
