"""create curriculum and ledger tables

Revision ID: 595589f5d80c
Revises:
Create Date: 2026-09-23 11:42:49.210957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "595589f5d80c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("curriculum_slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("study_time", sa.Time(), nullable=False),
        sa.Column(
            "baseline_card", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_plans_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
    )
    op.create_table(
        "topic_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("audit_brief", sa.Text(), nullable=False),
        sa.Column("unlock_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_topic_nodes_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_nodes")),
        sa.UniqueConstraint("plan_id", "day", name=op.f("uq_topic_nodes_plan_id_day")),
        sa.UniqueConstraint(
            "plan_id", "slug", name=op.f("uq_topic_nodes_plan_id_slug")
        ),
    )
    op.create_table(
        "ledger_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("shaky", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["topic_nodes.id"],
            name=op.f("fk_ledger_notes_node_id_topic_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_notes")),
    )
    op.create_index(
        op.f("ix_ledger_notes_node_id"), "ledger_notes", ["node_id"], unique=False
    )
    op.create_table(
        "topic_prerequisites",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "node_id <> prerequisite_id", name=op.f("ck_topic_prerequisites_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["topic_nodes.id"],
            name=op.f("fk_topic_prerequisites_node_id_topic_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["topic_nodes.id"],
            name=op.f("fk_topic_prerequisites_prerequisite_id_topic_nodes"),
        ),
        sa.PrimaryKeyConstraint(
            "node_id", "prerequisite_id", name=op.f("pk_topic_prerequisites")
        ),
    )
    op.create_table(
        "topic_vocabulary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("everyday", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["topic_nodes.id"],
            name=op.f("fk_topic_vocabulary_node_id_topic_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_vocabulary")),
    )
    op.create_index(
        op.f("ix_topic_vocabulary_node_id"),
        "topic_vocabulary",
        ["node_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # The knowledge ledger is append-only; enforce it where no code path can skip it.
    op.execute(
        """
        CREATE FUNCTION reject_ledger_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ledger_notes is append-only: % is not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_notes_no_update_or_delete
        BEFORE UPDATE OR DELETE ON ledger_notes
        FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER ledger_notes_no_truncate
        BEFORE TRUNCATE ON ledger_notes
        FOR EACH STATEMENT EXECUTE FUNCTION reject_ledger_mutation()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER ledger_notes_no_truncate ON ledger_notes")
    op.execute("DROP TRIGGER ledger_notes_no_update_or_delete ON ledger_notes")
    op.execute("DROP FUNCTION reject_ledger_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_vocabulary_node_id"), table_name="topic_vocabulary")
    op.drop_table("topic_vocabulary")
    op.drop_table("topic_prerequisites")
    op.drop_index(op.f("ix_ledger_notes_node_id"), table_name="ledger_notes")
    op.drop_table("ledger_notes")
    op.drop_table("topic_nodes")
    op.drop_table("plans")
    op.drop_table("users")
    # ### end Alembic commands ###
