"""add note embeddings

Revision ID: 707137be8092
Revises: 595589f5d80c
Create Date: 2026-09-23 12:08:48.530437

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "707137be8092"
down_revision: str | Sequence[str] | None = "595589f5d80c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_embeddings",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["ledger_notes.id"],
            name=op.f("fk_note_embeddings_note_id_ledger_notes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("note_id", "model", name=op.f("pk_note_embeddings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note_embeddings")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION vector")
