"""add message reactions

Revision ID: 8c9140ae4ecc
Revises: f3780bedc36d
Create Date: 2026-09-25 00:06:26.548937

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c9140ae4ecc"
down_revision: str | Sequence[str] | None = "f3780bedc36d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("reaction", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "reaction")
    # ### end Alembic commands ###
