"""add study session shares

Revision ID: 96c5684782ef
Revises: a675b4394cfd
Create Date: 2026-09-24 18:57:07.774347

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96c5684782ef"
down_revision: str | Sequence[str] | None = "a675b4394cfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("study_sessions", sa.Column("share", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("study_sessions", "share")
    # ### end Alembic commands ###
