"""add llm settings

Revision ID: a675b4394cfd
Revises: ada891ac86a6
Create Date: 2026-09-23 20:01:03.276467

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a675b4394cfd"
down_revision: str | Sequence[str] | None = "ada891ac86a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("models", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_llm_settings_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_settings")
    # ### end Alembic commands ###
