"""add message threads and proposals

Revision ID: ada891ac86a6
Revises: 2d886ad8383e
Create Date: 2026-09-23 19:53:27.591791

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ada891ac86a6"
down_revision: str | Sequence[str] | None = "2d886ad8383e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("thread", sa.Text(), server_default="chat", nullable=False),
    )
    op.add_column(
        "messages",
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "proposal")
    op.drop_column("messages", "thread")
    # ### end Alembic commands ###
