"""add turns

Revision ID: b86b6cbe84e2
Revises: 707137be8092
Create Date: 2026-09-23 12:22:49.035322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b86b6cbe84e2"
down_revision: str | Sequence[str] | None = "707137be8092"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("probe_run_id", sa.Text(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("fell_back", sa.Boolean(), nullable=False),
        sa.Column("final_reply", sa.Text(), nullable=False),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_turns_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    op.create_index(op.f("ix_turns_plan_id"), "turns", ["plan_id"], unique=False)
    op.create_index(
        op.f("ix_turns_probe_run_id"), "turns", ["probe_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turns_probe_run_id"), table_name="turns")
    op.drop_index(op.f("ix_turns_plan_id"), table_name="turns")
    op.drop_table("turns")
    # ### end Alembic commands ###
