"""add buddies

Revision ID: bc592a16af51
Revises: c72e24acfcf2
Create Date: 2026-09-23 18:30:33.190157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc592a16af51"
down_revision: str | Sequence[str] | None = "c72e24acfcf2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buddies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_buddies_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buddies")),
        sa.UniqueConstraint("user_id", name=op.f("uq_buddies_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("buddies")
    # ### end Alembic commands ###
