"""add dev clock

Revision ID: c72e24acfcf2
Revises: b86b6cbe84e2
Create Date: 2026-09-23 17:51:40.557368

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c72e24acfcf2"
down_revision: str | Sequence[str] | None = "b86b6cbe84e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dev_clock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offset", sa.Interval(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_dev_clock_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dev_clock")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dev_clock")
    # ### end Alembic commands ###
