"""add shaky resolutions

Revision ID: ccb22226e028
Revises: 3e0af845151c
Create Date: 2026-09-25 07:44:19.977536

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccb22226e028"
down_revision: str | Sequence[str] | None = "3e0af845151c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reflection_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("reflected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reflection_days_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reflection_days")),
        sa.UniqueConstraint(
            "user_id", "for_date", name=op.f("uq_reflection_days_user_id_for_date")
        ),
    )
    op.create_table(
        "shaky_resolutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("shaky", sa.Text(), nullable=False),
        sa.Column("insight", sa.Text(), nullable=False),
        sa.Column("written_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["ledger_notes.id"],
            name=op.f("fk_shaky_resolutions_note_id_ledger_notes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shaky_resolutions")),
    )
    op.create_index(
        op.f("ix_shaky_resolutions_note_id"),
        "shaky_resolutions",
        ["note_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Resolutions are knowledge too, so they are append-only like the notes.
    op.execute(
        """
        CREATE FUNCTION reject_resolution_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'shaky_resolutions is append-only: % is not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER shaky_resolutions_no_update_or_delete
        BEFORE UPDATE OR DELETE ON shaky_resolutions
        FOR EACH ROW EXECUTE FUNCTION reject_resolution_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER shaky_resolutions_no_truncate
        BEFORE TRUNCATE ON shaky_resolutions
        FOR EACH STATEMENT EXECUTE FUNCTION reject_resolution_mutation()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER shaky_resolutions_no_truncate ON shaky_resolutions")
    op.execute(
        "DROP TRIGGER shaky_resolutions_no_update_or_delete ON shaky_resolutions"
    )
    op.execute("DROP FUNCTION reject_resolution_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shaky_resolutions_note_id"), table_name="shaky_resolutions")
    op.drop_table("shaky_resolutions")
    op.drop_table("reflection_days")
    # ### end Alembic commands ###
