"""add study sessions

Revision ID: d9e6405561af
Revises: 234d61e05527
Create Date: 2026-09-23 19:19:40.278062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9e6405561af"
down_revision: str | Sequence[str] | None = "234d61e05527"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=True),
        sa.Column("attempts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["topic_nodes.id"],
            name=op.f("fk_study_sessions_node_id_topic_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["ledger_notes.id"],
            name=op.f("fk_study_sessions_note_id_ledger_notes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sessions")),
        sa.UniqueConstraint("node_id", name=op.f("uq_study_sessions_node_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("study_sessions")
    # ### end Alembic commands ###
