"""add rituals

Revision ID: ede27df4c6a8
Revises: 96c5684782ef
Create Date: 2026-09-24 18:59:35.933767

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ede27df4c6a8"
down_revision: str | Sequence[str] | None = "96c5684782ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rituals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=True),
        sa.Column("shaky", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_rituals_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["ledger_notes.id"],
            name=op.f("fk_rituals_note_id_ledger_notes"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_rituals_plan_id_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rituals")),
        sa.UniqueConstraint(
            "plan_id", "day", "kind", name=op.f("uq_rituals_plan_id_day_kind")
        ),
    )
    op.add_column(
        "messages",
        sa.Column("card", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "card")
    op.drop_table("rituals")
    # ### end Alembic commands ###
