// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AcceptData, AcceptErrors, AcceptResponses, AddCheckinData, AddCheckinResponses, AddPushTokenData, AddPushTokenErrors, AddPushTokenResponses, ChangeClockData, ChangeClockErrors, ChangeClockResponses, ChangePlanStudyTimeData, ChangePlanStudyTimeErrors, ChangePlanStudyTimeResponses, HealthData, HealthResponses, ListMessagesData, ListMessagesErrors, ListMessagesResponses, ListOnboardingMessagesData, ListOnboardingMessagesResponses, MessageStatusData, MessageStatusErrors, MessageStatusResponses, NextRitualData, NextRitualResponses, PausePlanData, PausePlanErrors, PausePlanResponses, PullTopicData, PullTopicErrors, PullTopicResponses, ReadBuddyData, ReadBuddyResponses, ReadClockData, ReadClockResponses, ReadNotebookData, ReadNotebookResponses, ReadNoteData, ReadNoteErrors, ReadNoteResponses, ReadRoadmapData, ReadRoadmapResponses, ReadSettingsData, ReadSettingsResponses, ReadTurnData, ReadTurnErrors, ReadTurnResponses, SendMessageData, SendMessageErrors, SendMessageResponses, SendOnboardingMessageData, SendOnboardingMessageErrors, SendOnboardingMessageResponses, StudyNowData, StudyNowResponses, TestConnectionData, TestConnectionResponses, UpdateSettingsData, UpdateSettingsErrors, UpdateSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Read Clock
 */
export const readClock = <ThrowOnError extends boolean = false>(options?: Options<ReadClockData, ThrowOnError>): RequestResult<ReadClockResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadClockResponses, unknown, ThrowOnError>({ url: '/dev/clock', ...options });

/**
 * Change Clock
 */
export const changeClock = <ThrowOnError extends boolean = false>(options: Options<ChangeClockData, ThrowOnError>): RequestResult<ChangeClockResponses, ChangeClockErrors, ThrowOnError> => (options.client ?? client).post<ChangeClockResponses, ChangeClockErrors, ThrowOnError>({
    url: '/dev/clock',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Study Now
 *
 * Run tonight's study: move to today's study time if it's earlier, then tick.
 */
export const studyNow = <ThrowOnError extends boolean = false>(options?: Options<StudyNowData, ThrowOnError>): RequestResult<StudyNowResponses, unknown, ThrowOnError> => (options?.client ?? client).post<StudyNowResponses, unknown, ThrowOnError>({ url: '/dev/study-now', ...options });

/**
 * Next Ritual
 *
 * Jump to the next morning, study or night review, then tick.
 */
export const nextRitual = <ThrowOnError extends boolean = false>(options?: Options<NextRitualData, ThrowOnError>): RequestResult<NextRitualResponses, unknown, ThrowOnError> => (options?.client ?? client).post<NextRitualResponses, unknown, ThrowOnError>({ url: '/dev/next-ritual', ...options });

/**
 * List Onboarding Messages
 */
export const listOnboardingMessages = <ThrowOnError extends boolean = false>(options?: Options<ListOnboardingMessagesData, ThrowOnError>): RequestResult<ListOnboardingMessagesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListOnboardingMessagesResponses, unknown, ThrowOnError>({ url: '/onboarding/messages', ...options });

/**
 * Send Onboarding Message
 *
 * One exchange of the co-planning chat. It waits for the audited reply, since
 * onboarding only shows typing dots.
 */
export const sendOnboardingMessage = <ThrowOnError extends boolean = false>(options: Options<SendOnboardingMessageData, ThrowOnError>): RequestResult<SendOnboardingMessageResponses, SendOnboardingMessageErrors, ThrowOnError> => (options.client ?? client).post<SendOnboardingMessageResponses, SendOnboardingMessageErrors, ThrowOnError>({
    url: '/onboarding/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Accept
 */
export const accept = <ThrowOnError extends boolean = false>(options: Options<AcceptData, ThrowOnError>): RequestResult<AcceptResponses, AcceptErrors, ThrowOnError> => (options.client ?? client).post<AcceptResponses, AcceptErrors, ThrowOnError>({
    url: '/onboarding/accept',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Messages
 */
export const listMessages = <ThrowOnError extends boolean = false>(options?: Options<ListMessagesData, ThrowOnError>): RequestResult<ListMessagesResponses, ListMessagesErrors, ThrowOnError> => (options?.client ?? client).get<ListMessagesResponses, ListMessagesErrors, ThrowOnError>({ url: '/chat/messages', ...options });

/**
 * Send Message
 *
 * Queue a message; poll its status for the stages and the audited reply.
 */
export const sendMessage = <ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>): RequestResult<SendMessageResponses, SendMessageErrors, ThrowOnError> => (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    url: '/chat/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Message Status
 */
export const messageStatus = <ThrowOnError extends boolean = false>(options: Options<MessageStatusData, ThrowOnError>): RequestResult<MessageStatusResponses, MessageStatusErrors, ThrowOnError> => (options.client ?? client).get<MessageStatusResponses, MessageStatusErrors, ThrowOnError>({ url: '/chat/messages/{message_id}', ...options });

/**
 * Read Turn
 *
 * The full trace behind one buddy reply, for the X-ray view.
 */
export const readTurn = <ThrowOnError extends boolean = false>(options: Options<ReadTurnData, ThrowOnError>): RequestResult<ReadTurnResponses, ReadTurnErrors, ThrowOnError> => (options.client ?? client).get<ReadTurnResponses, ReadTurnErrors, ThrowOnError>({ url: '/turns/{turn_id}', ...options });

/**
 * Read Buddy
 */
export const readBuddy = <ThrowOnError extends boolean = false>(options?: Options<ReadBuddyData, ThrowOnError>): RequestResult<ReadBuddyResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadBuddyResponses, unknown, ThrowOnError>({ url: '/buddy', ...options });

/**
 * Add Checkin
 *
 * "I studied today": marks the user's next topic done and returns it.
 */
export const addCheckin = <ThrowOnError extends boolean = false>(options?: Options<AddCheckinData, ThrowOnError>): RequestResult<AddCheckinResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AddCheckinResponses, unknown, ThrowOnError>({ url: '/progress/checkins', ...options });

/**
 * Add Push Token
 *
 * A phone that should get the buddy's rituals; registering again is harmless.
 */
export const addPushToken = <ThrowOnError extends boolean = false>(options: Options<AddPushTokenData, ThrowOnError>): RequestResult<AddPushTokenResponses, AddPushTokenErrors, ThrowOnError> => (options.client ?? client).post<AddPushTokenResponses, AddPushTokenErrors, ThrowOnError>({
    url: '/push/tokens',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Roadmap
 */
export const readRoadmap = <ThrowOnError extends boolean = false>(options?: Options<ReadRoadmapData, ThrowOnError>): RequestResult<ReadRoadmapResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadRoadmapResponses, unknown, ThrowOnError>({ url: '/roadmap', ...options });

/**
 * Pull Topic
 *
 * Pull a locked topic into the next free study slot.
 */
export const pullTopic = <ThrowOnError extends boolean = false>(options: Options<PullTopicData, ThrowOnError>): RequestResult<PullTopicResponses, PullTopicErrors, ThrowOnError> => (options.client ?? client).post<PullTopicResponses, PullTopicErrors, ThrowOnError>({
    url: '/roadmap/pull',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Notebook
 */
export const readNotebook = <ThrowOnError extends boolean = false>(options?: Options<ReadNotebookData, ThrowOnError>): RequestResult<ReadNotebookResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadNotebookResponses, unknown, ThrowOnError>({ url: '/notebook', ...options });

/**
 * Read Note
 */
export const readNote = <ThrowOnError extends boolean = false>(options: Options<ReadNoteData, ThrowOnError>): RequestResult<ReadNoteResponses, ReadNoteErrors, ThrowOnError> => (options.client ?? client).get<ReadNoteResponses, ReadNoteErrors, ThrowOnError>({ url: '/notebook/{note_id}', ...options });

/**
 * Pause Plan
 *
 * Move every topic still ahead back some days.
 */
export const pausePlan = <ThrowOnError extends boolean = false>(options: Options<PausePlanData, ThrowOnError>): RequestResult<PausePlanResponses, PausePlanErrors, ThrowOnError> => (options.client ?? client).post<PausePlanResponses, PausePlanErrors, ThrowOnError>({
    url: '/plan/pause',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change Plan Study Time
 */
export const changePlanStudyTime = <ThrowOnError extends boolean = false>(options: Options<ChangePlanStudyTimeData, ThrowOnError>): RequestResult<ChangePlanStudyTimeResponses, ChangePlanStudyTimeErrors, ThrowOnError> => (options.client ?? client).put<ChangePlanStudyTimeResponses, ChangePlanStudyTimeErrors, ThrowOnError>({
    url: '/plan/study-time',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Settings
 */
export const readSettings = <ThrowOnError extends boolean = false>(options?: Options<ReadSettingsData, ThrowOnError>): RequestResult<ReadSettingsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadSettingsResponses, unknown, ThrowOnError>({ url: '/settings', ...options });

/**
 * Update Settings
 */
export const updateSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateSettingsData, ThrowOnError>): RequestResult<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError> => (options.client ?? client).put<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
    url: '/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test Connection
 *
 * Lists the endpoint's models: proves the URL and key work without spending.
 */
export const testConnection = <ThrowOnError extends boolean = false>(options?: Options<TestConnectionData, ThrowOnError>): RequestResult<TestConnectionResponses, unknown, ThrowOnError> => (options?.client ?? client).post<TestConnectionResponses, unknown, ThrowOnError>({ url: '/settings/test', ...options });
