// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AcceptPlan
 */
export type AcceptPlan = {
    /**
     * Proposal Message Id
     */
    proposal_message_id: number;
    /**
     * Buddy Name
     */
    buddy_name: string;
};

/**
 * AdvanceClock
 */
export type AdvanceClock = {
    /**
     * Kind
     */
    kind: 'advance';
    /**
     * Hours
     */
    hours: number;
};

/**
 * AuditVerdict
 */
export type AuditVerdict = {
    verdict: Verdict;
    /**
     * Leaked Topic Slugs
     */
    leaked_topic_slugs: Array<string>;
    /**
     * Evidence
     */
    evidence: Array<string>;
    /**
     * Rationale
     */
    rationale: string;
};

/**
 * BuddyStatus
 */
export type BuddyStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Available
     */
    available: boolean;
    /**
     * Studying
     */
    studying: boolean;
};

/**
 * Category
 */
export type Category = 'curriculum' | 'out_of_plan' | 'off_topic' | 'meta' | 'crisis' | 'unsure';

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Id
     */
    id: number;
    speaker: Speaker;
    /**
     * Text
     */
    text: string;
    /**
     * At
     */
    at: string;
    stage: TurnStage | null;
    /**
     * Turn Id
     */
    turn_id: number | null;
};

/**
 * Classification
 */
export type Classification = {
    category: Category;
    /**
     * Topic Slugs
     */
    topic_slugs: Array<string>;
    /**
     * Rationale
     */
    rationale: string;
};

/**
 * ClockView
 */
export type ClockView = {
    /**
     * Now
     */
    now: string;
    /**
     * Real Time
     */
    real_time: boolean;
    /**
     * Day
     */
    day: number | null;
};

/**
 * ConnectionCheck
 */
export type ConnectionCheck = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Models
     */
    models: Array<string>;
    /**
     * Detail
     */
    detail: string | null;
};

/**
 * Directive
 */
export type Directive = {
    route: Route;
    /**
     * Answer Topics
     */
    answer_topics: Array<TopicRef>;
    /**
     * Deflect Topics
     */
    deflect_topics: Array<TopicRef>;
    /**
     * Ahead Topics
     */
    ahead_topics: Array<TopicRef>;
};

/**
 * DraftAttempt
 */
export type DraftAttempt = {
    /**
     * Reply
     */
    reply: string;
    audit: AuditVerdict;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * JumpToDay
 *
 * Move to a plan day, keeping the current local time of day.
 */
export type JumpToDay = {
    /**
     * Kind
     */
    kind: 'jump_to_day';
    /**
     * Day
     */
    day: number;
};

/**
 * LLMSettingsUpdate
 *
 * Only the fields sent change; the key is write-only.
 */
export type LlmSettingsUpdate = {
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Api Key
     */
    api_key?: null;
    models?: ModelsPerRole | null;
};

/**
 * LLMSettingsView
 */
export type LlmSettingsView = {
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Key Set
     */
    api_key_set: boolean;
    models: ModelsPerRole;
};

/**
 * MessageStatus
 */
export type MessageStatus = {
    message: ChatMessage;
    reply: ChatMessage | null;
};

/**
 * ModelsPerRole
 */
export type ModelsPerRole = {
    /**
     * Classifier
     */
    classifier: string;
    /**
     * Persona
     */
    persona: string;
    /**
     * Auditor
     */
    auditor: string;
    /**
     * Planner
     */
    planner: string;
    /**
     * Curator
     */
    curator: string;
};

/**
 * NotebookNote
 */
export type NotebookNote = {
    /**
     * Note Id
     */
    note_id: number;
    topic: TopicRef;
    /**
     * Body
     */
    body: string;
    /**
     * Shaky
     */
    shaky: Array<string>;
    /**
     * Sources
     */
    sources: Array<string>;
    /**
     * Written At
     */
    written_at: string;
};

/**
 * NotebookView
 */
export type NotebookView = {
    /**
     * Notes
     */
    notes: Array<NotebookNote>;
    /**
     * Sealed
     */
    sealed: Array<SealedDay>;
};

/**
 * OnboardingEntry
 *
 * One message of the onboarding chat, with the plan card a reply offered.
 */
export type OnboardingEntry = {
    message: ChatMessage;
    proposal: PlanProposal | null;
};

/**
 * OnboardingMessage
 */
export type OnboardingMessage = {
    /**
     * Text
     */
    text: string;
    /**
     * Timezone
     */
    timezone: string;
};

/**
 * OnboardingReply
 */
export type OnboardingReply = {
    message: ChatMessage;
    /**
     * Quick Replies
     */
    quick_replies: Array<string>;
    proposal: PlanProposal | null;
};

/**
 * PlanProposal
 */
export type PlanProposal = {
    /**
     * Curriculum Slug
     */
    curriculum_slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * Study Time
     */
    study_time: string;
    /**
     * Hours Per Day
     */
    hours_per_day: number;
    /**
     * Topics
     */
    topics: Array<TopicRef>;
};

/**
 * ResetClock
 */
export type ResetClock = {
    /**
     * Kind
     */
    kind: 'real_time';
};

/**
 * RetrievedNote
 */
export type RetrievedNote = {
    /**
     * Note Id
     */
    note_id: number;
    /**
     * Topic Slug
     */
    topic_slug: string;
    /**
     * Topic Title
     */
    topic_title: string;
    /**
     * Day
     */
    day: number;
    /**
     * Body
     */
    body: string;
    /**
     * Shaky
     */
    shaky: Array<string>;
    /**
     * Distance
     */
    distance: number;
};

/**
 * RoadmapTopic
 */
export type RoadmapTopic = {
    topic: TopicRef;
    /**
     * Unlocks At
     */
    unlocks_at: string;
    /**
     * Unlocked
     */
    unlocked: boolean;
    /**
     * Buddy Studied
     */
    buddy_studied: boolean;
    /**
     * User Studied
     */
    user_studied: boolean;
};

/**
 * RoadmapView
 */
export type RoadmapView = {
    /**
     * Plan Title
     */
    plan_title: string;
    /**
     * Day
     */
    day: number;
    /**
     * Topics
     */
    topics: Array<RoadmapTopic>;
};

/**
 * RoleModels
 */
export type RoleModels = {
    /**
     * Classifier
     */
    classifier: string;
    /**
     * Drafter
     */
    drafter: string;
    /**
     * Auditor
     */
    auditor: string;
};

/**
 * Route
 */
export type Route = 'answer' | 'deflect' | 'deflect_out_of_plan' | 'general' | 'crisis';

/**
 * SealedDay
 *
 * A day whose note isn't written yet: only its day and date, never its content.
 */
export type SealedDay = {
    /**
     * Day
     */
    day: number;
    /**
     * Unlocks At
     */
    unlocks_at: string;
};

/**
 * SendMessage
 */
export type SendMessage = {
    /**
     * Text
     */
    text: string;
};

/**
 * Speaker
 */
export type Speaker = 'user' | 'buddy';

/**
 * TopicRef
 */
export type TopicRef = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Day
     */
    day: number;
};

/**
 * TurnStage
 *
 * Where a user message is on its way to an audited reply.
 */
export type TurnStage = 'queued' | 'classifying' | 'writing' | 'checking' | 'answered' | 'failed';

/**
 * TurnTrace
 */
export type TurnTrace = {
    /**
     * Message
     */
    message: string;
    /**
     * At
     */
    at: string;
    classification: Classification;
    directive: Directive;
    /**
     * Retrieved
     */
    retrieved: Array<RetrievedNote>;
    /**
     * Attempts
     */
    attempts: Array<DraftAttempt>;
    /**
     * Final Reply
     */
    final_reply: string;
    /**
     * Fell Back
     */
    fell_back: boolean;
    models: RoleModels;
    /**
     * Latency Ms
     */
    latency_ms: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Verdict
 */
export type Verdict = 'pass' | 'leak';

/**
 * LLMSettingsUpdate
 *
 * Only the fields sent change; the key is write-only.
 */
export type LlmSettingsUpdateWritable = {
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    models?: ModelsPerRole | null;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ReadClockData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/clock';
};

export type ReadClockResponses = {
    /**
     * Successful Response
     */
    200: ClockView;
};

export type ReadClockResponse = ReadClockResponses[keyof ReadClockResponses];

export type ChangeClockData = {
    /**
     * Change
     */
    body: ({
        kind: 'advance';
    } & AdvanceClock) | ({
        kind: 'jump_to_day';
    } & JumpToDay) | ({
        kind: 'real_time';
    } & ResetClock);
    path?: never;
    query?: never;
    url: '/dev/clock';
};

export type ChangeClockErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeClockError = ChangeClockErrors[keyof ChangeClockErrors];

export type ChangeClockResponses = {
    /**
     * Successful Response
     */
    200: ClockView;
};

export type ChangeClockResponse = ChangeClockResponses[keyof ChangeClockResponses];

export type StudyNowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dev/study-now';
};

export type StudyNowResponses = {
    /**
     * Successful Response
     */
    200: ClockView;
};

export type StudyNowResponse = StudyNowResponses[keyof StudyNowResponses];

export type ListOnboardingMessagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/onboarding/messages';
};

export type ListOnboardingMessagesResponses = {
    /**
     * Response List Onboarding Messages
     *
     * Successful Response
     */
    200: Array<OnboardingEntry>;
};

export type ListOnboardingMessagesResponse = ListOnboardingMessagesResponses[keyof ListOnboardingMessagesResponses];

export type SendOnboardingMessageData = {
    body: OnboardingMessage;
    path?: never;
    query?: never;
    url: '/onboarding/messages';
};

export type SendOnboardingMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendOnboardingMessageError = SendOnboardingMessageErrors[keyof SendOnboardingMessageErrors];

export type SendOnboardingMessageResponses = {
    /**
     * Successful Response
     */
    200: OnboardingReply;
};

export type SendOnboardingMessageResponse = SendOnboardingMessageResponses[keyof SendOnboardingMessageResponses];

export type AcceptData = {
    body: AcceptPlan;
    path?: never;
    query?: never;
    url: '/onboarding/accept';
};

export type AcceptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptError = AcceptErrors[keyof AcceptErrors];

export type AcceptResponses = {
    /**
     * Successful Response
     */
    201: RoadmapView;
};

export type AcceptResponse = AcceptResponses[keyof AcceptResponses];

export type ListMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Before Id
         */
        before_id?: number | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/chat/messages';
};

export type ListMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * Response List Messages
     *
     * Successful Response
     */
    200: Array<ChatMessage>;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SendMessageData = {
    body: SendMessage;
    path?: never;
    query?: never;
    url: '/chat/messages';
};

export type SendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * Successful Response
     */
    202: ChatMessage;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type MessageStatusData = {
    body?: never;
    path: {
        /**
         * Message Id
         */
        message_id: number;
    };
    query?: never;
    url: '/chat/messages/{message_id}';
};

export type MessageStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MessageStatusError = MessageStatusErrors[keyof MessageStatusErrors];

export type MessageStatusResponses = {
    /**
     * Successful Response
     */
    200: MessageStatus;
};

export type MessageStatusResponse = MessageStatusResponses[keyof MessageStatusResponses];

export type ReadTurnData = {
    body?: never;
    path: {
        /**
         * Turn Id
         */
        turn_id: number;
    };
    query?: never;
    url: '/turns/{turn_id}';
};

export type ReadTurnErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTurnError = ReadTurnErrors[keyof ReadTurnErrors];

export type ReadTurnResponses = {
    /**
     * Successful Response
     */
    200: TurnTrace;
};

export type ReadTurnResponse = ReadTurnResponses[keyof ReadTurnResponses];

export type ReadBuddyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/buddy';
};

export type ReadBuddyResponses = {
    /**
     * Successful Response
     */
    200: BuddyStatus;
};

export type ReadBuddyResponse = ReadBuddyResponses[keyof ReadBuddyResponses];

export type AddCheckinData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/progress/checkins';
};

export type AddCheckinResponses = {
    /**
     * Successful Response
     */
    200: TopicRef;
};

export type AddCheckinResponse = AddCheckinResponses[keyof AddCheckinResponses];

export type ReadRoadmapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/roadmap';
};

export type ReadRoadmapResponses = {
    /**
     * Successful Response
     */
    200: RoadmapView;
};

export type ReadRoadmapResponse = ReadRoadmapResponses[keyof ReadRoadmapResponses];

export type ReadNotebookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notebook';
};

export type ReadNotebookResponses = {
    /**
     * Successful Response
     */
    200: NotebookView;
};

export type ReadNotebookResponse = ReadNotebookResponses[keyof ReadNotebookResponses];

export type ReadNoteData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: number;
    };
    query?: never;
    url: '/notebook/{note_id}';
};

export type ReadNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadNoteError = ReadNoteErrors[keyof ReadNoteErrors];

export type ReadNoteResponses = {
    /**
     * Successful Response
     */
    200: NotebookNote;
};

export type ReadNoteResponse = ReadNoteResponses[keyof ReadNoteResponses];

export type ReadSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type ReadSettingsResponses = {
    /**
     * Successful Response
     */
    200: LlmSettingsView;
};

export type ReadSettingsResponse = ReadSettingsResponses[keyof ReadSettingsResponses];

export type UpdateSettingsData = {
    body: LlmSettingsUpdateWritable;
    path?: never;
    query?: never;
    url: '/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * Successful Response
     */
    200: LlmSettingsView;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type TestConnectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/test';
};

export type TestConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionCheck;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];
