// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * AuditVerdict
 */
export type AuditVerdict = {
    verdict: Verdict;
    /**
     * Leaked Topic Slugs
     */
    leaked_topic_slugs?: Array<string>;
    /**
     * Evidence
     */
    evidence?: Array<string>;
    /**
     * Rationale
     */
    rationale: string;
};

/**
 * Category
 */
export type Category = 'curriculum' | 'out_of_plan' | 'off_topic' | 'meta' | 'unsure';

/**
 * ChatTurn
 */
export type ChatTurn = {
    speaker: Speaker;
    /**
     * Text
     */
    text: string;
};

/**
 * Classification
 */
export type Classification = {
    category: Category;
    /**
     * Topic Slugs
     */
    topic_slugs?: Array<string>;
    /**
     * Rationale
     */
    rationale: string;
};

/**
 * Directive
 */
export type Directive = {
    route: Route;
    /**
     * Answer Topics
     */
    answer_topics?: Array<TopicRef>;
    /**
     * Deflect Topics
     */
    deflect_topics?: Array<TopicRef>;
};

/**
 * DraftAttempt
 */
export type DraftAttempt = {
    /**
     * Reply
     */
    reply: string;
    audit: AuditVerdict;
};

/**
 * RetrievedNote
 */
export type RetrievedNote = {
    /**
     * Note Id
     */
    note_id: number;
    /**
     * Topic Slug
     */
    topic_slug: string;
    /**
     * Topic Title
     */
    topic_title: string;
    /**
     * Day
     */
    day: number;
    /**
     * Body
     */
    body: string;
    /**
     * Shaky
     */
    shaky: Array<string>;
    /**
     * Distance
     */
    distance: number;
};

/**
 * RoadmapEntry
 */
export type RoadmapEntry = {
    topic: TopicRef;
    /**
     * Unlocked
     */
    unlocked: boolean;
};

/**
 * RoleModels
 */
export type RoleModels = {
    /**
     * Classifier
     */
    classifier: string;
    /**
     * Drafter
     */
    drafter: string;
    /**
     * Auditor
     */
    auditor: string;
};

/**
 * Route
 */
export type Route = 'answer' | 'deflect' | 'deflect_out_of_plan' | 'general';

/**
 * Speaker
 */
export type Speaker = 'user' | 'buddy';

/**
 * StudyNote
 */
export type StudyNote = {
    /**
     * Body
     */
    body: string;
    /**
     * Shaky
     */
    shaky: Array<string>;
    /**
     * Sources
     */
    sources: Array<string>;
};

/**
 * TopicRef
 */
export type TopicRef = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Day
     */
    day: number;
};

/**
 * TurnTrace
 */
export type TurnTrace = {
    /**
     * Message
     */
    message: string;
    /**
     * At
     */
    at: string;
    classification: Classification;
    directive: Directive;
    /**
     * Retrieved
     */
    retrieved: Array<RetrievedNote>;
    /**
     * Attempts
     */
    attempts: Array<DraftAttempt>;
    /**
     * Final Reply
     */
    final_reply: string;
    /**
     * Fell Back
     */
    fell_back: boolean;
    models: RoleModels;
    /**
     * Latency Ms
     */
    latency_ms: number;
};

/**
 * Verdict
 */
export type Verdict = 'pass' | 'leak';

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
