// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { accept, addCheckin, addPushToken, changeClock, changePlanStudyTime, health, listMessages, listOnboardingMessages, messageStatus, nextRitual, type Options, pausePlan, pullTopic, readBuddy, readClock, readNote, readNotebook, readRoadmap, readSettings, readTurn, sendMessage, sendOnboardingMessage, studyNow, testConnection, updateSettings } from '../sdk.gen';
import type { AcceptData, AcceptError, AcceptResponse, AddCheckinData, AddCheckinResponse, AddPushTokenData, AddPushTokenError, AddPushTokenResponse, ChangeClockData, ChangeClockError, ChangeClockResponse, ChangePlanStudyTimeData, ChangePlanStudyTimeError, ChangePlanStudyTimeResponse, HealthData, HealthResponse2, ListMessagesData, ListMessagesError, ListMessagesResponse, ListOnboardingMessagesData, ListOnboardingMessagesResponse, MessageStatusData, MessageStatusError, MessageStatusResponse, NextRitualData, NextRitualResponse, PausePlanData, PausePlanError, PausePlanResponse, PullTopicData, PullTopicError, PullTopicResponse, ReadBuddyData, ReadBuddyResponse, ReadClockData, ReadClockResponse, ReadNotebookData, ReadNotebookResponse, ReadNoteData, ReadNoteError, ReadNoteResponse, ReadRoadmapData, ReadRoadmapResponse, ReadSettingsData, ReadSettingsResponse, ReadTurnData, ReadTurnError, ReadTurnResponse, SendMessageData, SendMessageError, SendMessageResponse, SendOnboardingMessageData, SendOnboardingMessageError, SendOnboardingMessageResponse, StudyNowData, StudyNowResponse, TestConnectionData, TestConnectionResponse, UpdateSettingsData, UpdateSettingsError, UpdateSettingsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse2, DefaultError, HealthResponse2, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const readClockQueryKey = (options?: Options<ReadClockData>) => createQueryKey('readClock', options);

/**
 * Read Clock
 */
export const readClockOptions = (options?: Options<ReadClockData>) => queryOptions<ReadClockResponse, DefaultError, ReadClockResponse, ReturnType<typeof readClockQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readClock({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readClockQueryKey(options)
});

/**
 * Change Clock
 */
export const changeClockMutation = (options?: Partial<Options<ChangeClockData>>): UseMutationOptions<ChangeClockResponse, ChangeClockError, Options<ChangeClockData>> => {
    const mutationOptions: UseMutationOptions<ChangeClockResponse, ChangeClockError, Options<ChangeClockData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changeClock({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Study Now
 *
 * Run tonight's study: move to today's study time if it's earlier, then tick.
 */
export const studyNowMutation = (options?: Partial<Options<StudyNowData>>): UseMutationOptions<StudyNowResponse, DefaultError, Options<StudyNowData>> => {
    const mutationOptions: UseMutationOptions<StudyNowResponse, DefaultError, Options<StudyNowData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await studyNow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Next Ritual
 *
 * Jump to the next morning, study or night review, then tick.
 */
export const nextRitualMutation = (options?: Partial<Options<NextRitualData>>): UseMutationOptions<NextRitualResponse, DefaultError, Options<NextRitualData>> => {
    const mutationOptions: UseMutationOptions<NextRitualResponse, DefaultError, Options<NextRitualData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await nextRitual({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listOnboardingMessagesQueryKey = (options?: Options<ListOnboardingMessagesData>) => createQueryKey('listOnboardingMessages', options);

/**
 * List Onboarding Messages
 */
export const listOnboardingMessagesOptions = (options?: Options<ListOnboardingMessagesData>) => queryOptions<ListOnboardingMessagesResponse, DefaultError, ListOnboardingMessagesResponse, ReturnType<typeof listOnboardingMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listOnboardingMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listOnboardingMessagesQueryKey(options)
});

/**
 * Send Onboarding Message
 *
 * One exchange of the co-planning chat. It waits for the audited reply, since
 * onboarding only shows typing dots.
 */
export const sendOnboardingMessageMutation = (options?: Partial<Options<SendOnboardingMessageData>>): UseMutationOptions<SendOnboardingMessageResponse, SendOnboardingMessageError, Options<SendOnboardingMessageData>> => {
    const mutationOptions: UseMutationOptions<SendOnboardingMessageResponse, SendOnboardingMessageError, Options<SendOnboardingMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendOnboardingMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Accept
 */
export const acceptMutation = (options?: Partial<Options<AcceptData>>): UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> => {
    const mutationOptions: UseMutationOptions<AcceptResponse, AcceptError, Options<AcceptData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await accept({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listMessagesQueryKey = (options?: Options<ListMessagesData>) => createQueryKey('listMessages', options);

/**
 * List Messages
 */
export const listMessagesOptions = (options?: Options<ListMessagesData>) => queryOptions<ListMessagesResponse, ListMessagesError, ListMessagesResponse, ReturnType<typeof listMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMessagesQueryKey(options)
});

/**
 * Send Message
 *
 * Queue a message; poll its status for the stages and the audited reply.
 */
export const sendMessageMutation = (options?: Partial<Options<SendMessageData>>): UseMutationOptions<SendMessageResponse, SendMessageError, Options<SendMessageData>> => {
    const mutationOptions: UseMutationOptions<SendMessageResponse, SendMessageError, Options<SendMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const messageStatusQueryKey = (options: Options<MessageStatusData>) => createQueryKey('messageStatus', options);

/**
 * Message Status
 */
export const messageStatusOptions = (options: Options<MessageStatusData>) => queryOptions<MessageStatusResponse, MessageStatusError, MessageStatusResponse, ReturnType<typeof messageStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await messageStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: messageStatusQueryKey(options)
});

export const readTurnQueryKey = (options: Options<ReadTurnData>) => createQueryKey('readTurn', options);

/**
 * Read Turn
 *
 * The full trace behind one buddy reply, for the X-ray view.
 */
export const readTurnOptions = (options: Options<ReadTurnData>) => queryOptions<ReadTurnResponse, ReadTurnError, ReadTurnResponse, ReturnType<typeof readTurnQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readTurn({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readTurnQueryKey(options)
});

export const readBuddyQueryKey = (options?: Options<ReadBuddyData>) => createQueryKey('readBuddy', options);

/**
 * Read Buddy
 */
export const readBuddyOptions = (options?: Options<ReadBuddyData>) => queryOptions<ReadBuddyResponse, DefaultError, ReadBuddyResponse, ReturnType<typeof readBuddyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readBuddy({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readBuddyQueryKey(options)
});

/**
 * Add Checkin
 *
 * "I studied today": marks the user's next topic done and returns it.
 */
export const addCheckinMutation = (options?: Partial<Options<AddCheckinData>>): UseMutationOptions<AddCheckinResponse, DefaultError, Options<AddCheckinData>> => {
    const mutationOptions: UseMutationOptions<AddCheckinResponse, DefaultError, Options<AddCheckinData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addCheckin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add Push Token
 *
 * A phone that should get the buddy's rituals; registering again is harmless.
 */
export const addPushTokenMutation = (options?: Partial<Options<AddPushTokenData>>): UseMutationOptions<AddPushTokenResponse, AddPushTokenError, Options<AddPushTokenData>> => {
    const mutationOptions: UseMutationOptions<AddPushTokenResponse, AddPushTokenError, Options<AddPushTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addPushToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readRoadmapQueryKey = (options?: Options<ReadRoadmapData>) => createQueryKey('readRoadmap', options);

/**
 * Read Roadmap
 */
export const readRoadmapOptions = (options?: Options<ReadRoadmapData>) => queryOptions<ReadRoadmapResponse, DefaultError, ReadRoadmapResponse, ReturnType<typeof readRoadmapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRoadmap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRoadmapQueryKey(options)
});

/**
 * Pull Topic
 *
 * Pull a locked topic into the next free study slot.
 */
export const pullTopicMutation = (options?: Partial<Options<PullTopicData>>): UseMutationOptions<PullTopicResponse, PullTopicError, Options<PullTopicData>> => {
    const mutationOptions: UseMutationOptions<PullTopicResponse, PullTopicError, Options<PullTopicData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pullTopic({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readNotebookQueryKey = (options?: Options<ReadNotebookData>) => createQueryKey('readNotebook', options);

/**
 * Read Notebook
 */
export const readNotebookOptions = (options?: Options<ReadNotebookData>) => queryOptions<ReadNotebookResponse, DefaultError, ReadNotebookResponse, ReturnType<typeof readNotebookQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readNotebook({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readNotebookQueryKey(options)
});

export const readNoteQueryKey = (options: Options<ReadNoteData>) => createQueryKey('readNote', options);

/**
 * Read Note
 */
export const readNoteOptions = (options: Options<ReadNoteData>) => queryOptions<ReadNoteResponse, ReadNoteError, ReadNoteResponse, ReturnType<typeof readNoteQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readNote({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readNoteQueryKey(options)
});

/**
 * Pause Plan
 *
 * Move every topic still ahead back some days.
 */
export const pausePlanMutation = (options?: Partial<Options<PausePlanData>>): UseMutationOptions<PausePlanResponse, PausePlanError, Options<PausePlanData>> => {
    const mutationOptions: UseMutationOptions<PausePlanResponse, PausePlanError, Options<PausePlanData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pausePlan({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change Plan Study Time
 */
export const changePlanStudyTimeMutation = (options?: Partial<Options<ChangePlanStudyTimeData>>): UseMutationOptions<ChangePlanStudyTimeResponse, ChangePlanStudyTimeError, Options<ChangePlanStudyTimeData>> => {
    const mutationOptions: UseMutationOptions<ChangePlanStudyTimeResponse, ChangePlanStudyTimeError, Options<ChangePlanStudyTimeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePlanStudyTime({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readSettingsQueryKey = (options?: Options<ReadSettingsData>) => createQueryKey('readSettings', options);

/**
 * Read Settings
 */
export const readSettingsOptions = (options?: Options<ReadSettingsData>) => queryOptions<ReadSettingsResponse, DefaultError, ReadSettingsResponse, ReturnType<typeof readSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readSettings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readSettingsQueryKey(options)
});

/**
 * Update Settings
 */
export const updateSettingsMutation = (options?: Partial<Options<UpdateSettingsData>>): UseMutationOptions<UpdateSettingsResponse, UpdateSettingsError, Options<UpdateSettingsData>> => {
    const mutationOptions: UseMutationOptions<UpdateSettingsResponse, UpdateSettingsError, Options<UpdateSettingsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSettings({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Test Connection
 *
 * Lists the endpoint's models: proves the URL and key work without spending.
 */
export const testConnectionMutation = (options?: Partial<Options<TestConnectionData>>): UseMutationOptions<TestConnectionResponse, DefaultError, Options<TestConnectionData>> => {
    const mutationOptions: UseMutationOptions<TestConnectionResponse, DefaultError, Options<TestConnectionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await testConnection({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
